### ISSUE TITLE
AWS 크롤링 실패 에러

### ISSUE THREAD

**Issue by item4** [item4/yui#44]
```pytb
Traceback (most recent call last):
  File "/home/item4/.virtualenvs/yui/lib/python3.6/site-packages/aiohttp/connector.py", line 378, in connect
    proto = yield from self._create_connection(req)
  File "/home/item4/.virtualenvs/yui/lib/python3.6/site-packages/aiohttp/connector.py", line 687, in _create_connection
    _, proto = yield from self._create_direct_connection(req)
  File "/home/item4/.virtualenvs/yui/lib/python3.6/site-packages/aiohttp/connector.py", line 698, in _create_direct_connection
    hosts = yield from self._resolve_host(req.url.raw_host, req.port)
  File "/home/item4/.virtualenvs/yui/lib/python3.6/site-packages/aiohttp/connector.py", line 669, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/home/item4/.virtualenvs/yui/lib/python3.6/site-packages/aiohttp/resolver.py", line 31, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/home/item4/.pyenv/versions/3.6.1/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/item4/.pyenv/versions/3.6.1/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/item4/yui/yui/bot.py", line 89, in task
    await c.func(**kw)
  File "/home/item4/yui/yui/handlers/aws.py", line 28, in crawl
    async with session.get(url) as res:
  File "/home/item4/.virtualenvs/yui/lib/python3.6/site-packages/aiohttp/client.py", line 603, in __aenter__
    self._resp = yield from self._coro
  File "/home/item4/.virtualenvs/yui/lib/python3.6/site-packages/aiohttp/client.py", line 231, in _request
    conn = yield from self._connector.connect(req)
  File "/home/item4/.virtualenvs/yui/lib/python3.6/site-packages/aiohttp/connector.py", line 383, in connect
    .format(key, exc.strerror)) from exc
aiohttp.client_exceptions.ClientConnectorError: [Errno -2] Cannot connect to host www.kma.go.kr:80 ssl:False [Name or service not known]
```

**Comment by item4** [comment]
```pytb
Traceback (most recent call last):
  File "/home/item4/yui/yui/bot.py", line 89, in task
    await c.func(**kw)
  File "/home/item4/yui/yui/handlers/aws.py", line 33, in crawl
    h.cssselect('span.ehead')[0].text_content().replace(
IndexError: list index out of range
```
